"""
Orchestrates a single chat turn end to end:

state lookup -> prompt build -> graph run (guardrails + agent + tools)
-> state persist -> typed response.
"""

from __future__ import annotations

import structlog
from langchain_core.messages import AIMessage

from app.ai.graph import chat_graph
from app.core.config import settings
from app.core.exceptions import LLMProviderError
from app.schemas.chat import ChatRequest, ChatResponse, Role, ToolCallRecord
from app.services import prompt_builder, state_manager

log = structlog.get_logger(__name__)


async def handle_chat_turn(
    request: ChatRequest, *, request_id: str | None = None
) -> ChatResponse:
    # Fetch previous conversation history for the session
    history = await state_manager.get_history(request.session_id)

    # Build the final prompt messages using history, metadata, and optional RAG context
    messages = await prompt_builder.build_messages(
        user_message=request.message,
        history=history,
        additional_context=request.metadata,
        use_rag=request.use_rag,
    )

    try:
        # Run chat graph which handles guardrails, agent logic, and tools
        result = await chat_graph.ainvoke(
            {
                "messages": messages,
                "user_id": request.user_id,
                "session_id": request.session_id,
                "tool_calls": [],
            }
        )
    except Exception as exc:
        # Log graph failures and convert them into a controlled application error
        log.error(
            "chat_graph_failed",
            session_id=request.session_id,
            error=str(exc),
            exc_info=True,
        )
        raise LLMProviderError(
            "Failed to generate a response.", details={"reason": str(exc)}
        ) from exc

    # Extract the final AIMessage generated by the graph
    final_ai_message = next(
        (m for m in reversed(result["messages"]) if isinstance(m, AIMessage)), None
    )

    # Convert AIMessage content into response text
    final_text = str(final_ai_message.content) if final_ai_message else ""

    # Store user message and assistant response in session state
    await state_manager.append_turn(
        request.session_id, request.user_id, Role.user, request.message
    )
    await state_manager.append_turn(
        request.session_id, request.user_id, Role.assistant, final_text
    )

    # Convert raw tool call data into typed ToolCallRecord objects
    tool_calls = [ToolCallRecord(**tc) for tc in result.get("tool_calls", [])]

    # Return structured chat response
    return ChatResponse(
        session_id=request.session_id,
        message=final_text,
        tool_calls=tool_calls,
        model=settings.model_name,
        request_id=request_id,
    )
